In [98]:
import numpy as np
import pandas as pd

In [99]:
df=pd.read_csv('../DataSets/B_train.csv')
df

Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
0              FDA15        9.300          Low Fat         0.016047   
1              DRC01        5.920          Regular         0.019278   
2              FDN15       17.500          Low Fat         0.016760   
3              FDX07       19.200          Regular         0.000000   
4              NCD19        8.930          Low Fat         0.000000   
...              ...          ...              ...              ...   
8518           FDF22        6.865          Low Fat         0.056783   
8519           FDS36        8.380          Regular         0.046982   
8520           NCJ29       10.600          Low Fat         0.035186   
8521           FDN46        7.210          Regular         0.145221   
8522           DRG01       14.800          Low Fat         0.044878   

                  Item_Type  Item_MRP Outlet_Identifier  \
0                     Dairy  249.8092            OUT049   
1               Soft Drinks   48.2692            OUT018   
2                      Meat  141.6180            OUT049   
3     Fruits and Vegetables  182.0950            OUT010   
4                 Household   53.8614            OUT013   
...                     ...       ...               ...   
8518            Snack Foods  214.5218            OUT013   
8519           Baking Goods  108.1570            OUT045   
8520     Health and Hygiene   85.1224            OUT035   
8521            Snack Foods  103.1332            OUT018   
8522            Soft Drinks   75.4670            OUT046   

      Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
0                          1999      Medium               Tier 1   
1                          2009      Medium               Tier 3   
2                          1999      Medium               Tier 1   
3                          1998         NaN               Tier 3   
4                          1987        High               Tier 3   
...                         ...         ...                  ...   
8518                       1987        High               Tier 3   
8519                       2002         NaN               Tier 2   
8520                       2004       Small               Tier 2   
8521                       2009      Medium               Tier 3   
8522                       1997       Small               Tier 1   

            Outlet_Type  Item_Outlet_Sales  
0     Supermarket Type1          3735.1380  
1     Supermarket Type2           443.4228  
2     Supermarket Type1          2097.2700  
3         Grocery Store           732.3800  
4     Supermarket Type1           994.7052  
...                 ...                ...  
8518  Supermarket Type1          2778.3834  
8519  Supermarket Type1           549.2850  
8520  Supermarket Type1          1193.1136  
8521  Supermarket Type2          1845.5976  
8522  Supermarket Type1           765.6700  

[8523 rows x 12 columns]

In [100]:
df.isnull().sum()


Item_Identifier                 0
Item_Weight                  1463
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [101]:
df.Outlet_Size.value_counts()

Medium    2793
Small     2388
High       932
Name: Outlet_Size, dtype: int64

In [102]:
df.Item_Weight=df.Item_Weight.fillna(12.8)
df.Outlet_Size=df.Outlet_Size.fillna('Unknown')

In [103]:
df.dtypes

Item_Identifier               object
Item_Weight                  float64
Item_Fat_Content              object
Item_Visibility              float64
Item_Type                     object
Item_MRP                     float64
Outlet_Identifier             object
Outlet_Establishment_Year      int64
Outlet_Size                   object
Outlet_Location_Type          object
Outlet_Type                   object
Item_Outlet_Sales            float64
dtype: object

In [104]:
dt=df.drop(['Item_Identifier','Outlet_Identifier','Outlet_Establishment_Year'],axis=1)

In [105]:
dt

Item_Weight Item_Fat_Content  Item_Visibility              Item_Type  \
0           9.300          Low Fat         0.016047                  Dairy   
1           5.920          Regular         0.019278            Soft Drinks   
2          17.500          Low Fat         0.016760                   Meat   
3          19.200          Regular         0.000000  Fruits and Vegetables   
4           8.930          Low Fat         0.000000              Household   
...           ...              ...              ...                    ...   
8518        6.865          Low Fat         0.056783            Snack Foods   
8519        8.380          Regular         0.046982           Baking Goods   
8520       10.600          Low Fat         0.035186     Health and Hygiene   
8521        7.210          Regular         0.145221            Snack Foods   
8522       14.800          Low Fat         0.044878            Soft Drinks   

      Item_MRP Outlet_Size Outlet_Location_Type        Outlet_Type  \
0     249.8092      Medium               Tier 1  Supermarket Type1   
1      48.2692      Medium               Tier 3  Supermarket Type2   
2     141.6180      Medium               Tier 1  Supermarket Type1   
3     182.0950     Unknown               Tier 3      Grocery Store   
4      53.8614        High               Tier 3  Supermarket Type1   
...        ...         ...                  ...                ...   
8518  214.5218        High               Tier 3  Supermarket Type1   
8519  108.1570     Unknown               Tier 2  Supermarket Type1   
8520   85.1224       Small               Tier 2  Supermarket Type1   
8521  103.1332      Medium               Tier 3  Supermarket Type2   
8522   75.4670       Small               Tier 1  Supermarket Type1   

      Item_Outlet_Sales  
0             3735.1380  
1              443.4228  
2             2097.2700  
3              732.3800  
4              994.7052  
...                 ...  
8518          2778.3834  
8519           549.2850  
8520          1193.1136  
8521          1845.5976  
8522           765.6700  

[8523 rows x 9 columns]

In [106]:
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()

In [107]:
dt.Item_Type=label.fit_transform(dt.Item_Type)
dt.Outlet_Size=label.fit_transform(dt.Outlet_Size)
dt.Outlet_Location_Type=label.fit_transform(dt.Outlet_Location_Type)
dt.Outlet_Type=label.fit_transform(dt.Outlet_Type)
dt.Item_Fat_Content=label.fit_transform(dt.Item_Fat_Content)

In [108]:
dt

Item_Weight  Item_Fat_Content  Item_Visibility  Item_Type  Item_MRP  \
0           9.300                 1         0.016047          4  249.8092   
1           5.920                 2         0.019278         14   48.2692   
2          17.500                 1         0.016760         10  141.6180   
3          19.200                 2         0.000000          6  182.0950   
4           8.930                 1         0.000000          9   53.8614   
...           ...               ...              ...        ...       ...   
8518        6.865                 1         0.056783         13  214.5218   
8519        8.380                 2         0.046982          0  108.1570   
8520       10.600                 1         0.035186          8   85.1224   
8521        7.210                 2         0.145221         13  103.1332   
8522       14.800                 1         0.044878         14   75.4670   

      Outlet_Size  Outlet_Location_Type  Outlet_Type  Item_Outlet_Sales  
0               1                     0            1          3735.1380  
1               1                     2            2           443.4228  
2               1                     0            1          2097.2700  
3               3                     2            0           732.3800  
4               0                     2            1           994.7052  
...           ...                   ...          ...                ...  
8518            0                     2            1          2778.3834  
8519            3                     1            1           549.2850  
8520            2                     1            1          1193.1136  
8521            1                     2            2          1845.5976  
8522            2                     0            1           765.6700  

[8523 rows x 9 columns]

In [109]:
x=dt.drop('Item_Outlet_Sales',axis=1).values
x

array([[9.30000000e+00, 1.00000000e+00, 1.60473010e-02, ...,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [5.92000000e+00, 2.00000000e+00, 1.92782160e-02, ...,
        1.00000000e+00, 2.00000000e+00, 2.00000000e+00],
       [1.75000000e+01, 1.00000000e+00, 1.67600750e-02, ...,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       ...,
       [1.06000000e+01, 1.00000000e+00, 3.51862710e-02, ...,
        2.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       [7.21000000e+00, 2.00000000e+00, 1.45220646e-01, ...,
        1.00000000e+00, 2.00000000e+00, 2.00000000e+00],
       [1.48000000e+01, 1.00000000e+00, 4.48782800e-02, ...,
        2.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

In [110]:
y=dt['Item_Outlet_Sales'].values
y

array([3735.138 ,  443.4228, 2097.27  , ..., 1193.1136, 1845.5976,
        765.67  ])

In [111]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.25)

In [112]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(xtrain,ytrain)

LinearRegression()

In [113]:
ypred=model.predict(xtest)
ypred

array([ 6.54916960e+02, -4.15518346e+00, -3.32317382e+02, ...,
        8.91201460e+02,  4.18866642e+03,  1.91764297e+03])

In [114]:
from sklearn.metrics import r2_score,mean_squared_error
r2=r2_score(ypred,ytest)
r2

-0.06891406607290307

In [115]:
mse=mean_squared_error(ypred,ytest)
mse

1462953.4202107245

In [116]:
rmse = np.sqrt(mse)

In [117]:
rmse

1209.5261139019383

In [118]:
dr=pd.read_csv('../DataSets/B_test.csv')
dr

Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
0              FDW58       20.750          Low Fat         0.007565   
1              FDW14        8.300              reg         0.038428   
2              NCN55       14.600          Low Fat         0.099575   
3              FDQ58        7.315          Low Fat         0.015388   
4              FDY38          NaN          Regular         0.118599   
...              ...          ...              ...              ...   
5676           FDB58       10.500          Regular         0.013496   
5677           FDD47        7.600          Regular         0.142991   
5678           NCO17       10.000          Low Fat         0.073529   
5679           FDJ26       15.300          Regular         0.000000   
5680           FDU37        9.500          Regular         0.104720   

               Item_Type  Item_MRP Outlet_Identifier  \
0            Snack Foods  107.8622            OUT049   
1                  Dairy   87.3198            OUT017   
2                 Others  241.7538            OUT010   
3            Snack Foods  155.0340            OUT017   
4                  Dairy  234.2300            OUT027   
...                  ...       ...               ...   
5676         Snack Foods  141.3154            OUT046   
5677       Starchy Foods  169.1448            OUT018   
5678  Health and Hygiene  118.7440            OUT045   
5679              Canned  214.6218            OUT017   
5680              Canned   79.7960            OUT045   

      Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
0                          1999      Medium               Tier 1   
1                          2007         NaN               Tier 2   
2                          1998         NaN               Tier 3   
3                          2007         NaN               Tier 2   
4                          1985      Medium               Tier 3   
...                         ...         ...                  ...   
5676                       1997       Small               Tier 1   
5677                       2009      Medium               Tier 3   
5678                       2002         NaN               Tier 2   
5679                       2007         NaN               Tier 2   
5680                       2002         NaN               Tier 2   

            Outlet_Type  
0     Supermarket Type1  
1     Supermarket Type1  
2         Grocery Store  
3     Supermarket Type1  
4     Supermarket Type3  
...                 ...  
5676  Supermarket Type1  
5677  Supermarket Type2  
5678  Supermarket Type1  
5679  Supermarket Type1  
5680  Supermarket Type1  

[5681 rows x 11 columns]

In [119]:
dr.isnull().sum()

Item_Identifier                 0
Item_Weight                   976
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  1606
Outlet_Location_Type            0
Outlet_Type                     0
dtype: int64

In [120]:
dr.Item_Weight=dr.Item_Weight.fillna(12.8)
dr.Outlet_Size=dr.Outlet_Size.fillna('Unknown')

In [121]:
dh=dr.drop(['Item_Identifier','Outlet_Identifier','Outlet_Establishment_Year'],axis=1)

In [122]:
dh

Item_Weight Item_Fat_Content  Item_Visibility           Item_Type  \
0          20.750          Low Fat         0.007565         Snack Foods   
1           8.300              reg         0.038428               Dairy   
2          14.600          Low Fat         0.099575              Others   
3           7.315          Low Fat         0.015388         Snack Foods   
4          12.800          Regular         0.118599               Dairy   
...           ...              ...              ...                 ...   
5676       10.500          Regular         0.013496         Snack Foods   
5677        7.600          Regular         0.142991       Starchy Foods   
5678       10.000          Low Fat         0.073529  Health and Hygiene   
5679       15.300          Regular         0.000000              Canned   
5680        9.500          Regular         0.104720              Canned   

      Item_MRP Outlet_Size Outlet_Location_Type        Outlet_Type  
0     107.8622      Medium               Tier 1  Supermarket Type1  
1      87.3198     Unknown               Tier 2  Supermarket Type1  
2     241.7538     Unknown               Tier 3      Grocery Store  
3     155.0340     Unknown               Tier 2  Supermarket Type1  
4     234.2300      Medium               Tier 3  Supermarket Type3  
...        ...         ...                  ...                ...  
5676  141.3154       Small               Tier 1  Supermarket Type1  
5677  169.1448      Medium               Tier 3  Supermarket Type2  
5678  118.7440     Unknown               Tier 2  Supermarket Type1  
5679  214.6218     Unknown               Tier 2  Supermarket Type1  
5680   79.7960     Unknown               Tier 2  Supermarket Type1  

[5681 rows x 8 columns]

In [123]:
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()

In [124]:
dh.Item_Type=label.fit_transform(dh.Item_Type)
dh.Outlet_Size=label.fit_transform(dh.Outlet_Size)
dh.Outlet_Location_Type=label.fit_transform(dh.Outlet_Location_Type)
dh.Outlet_Type=label.fit_transform(dh.Outlet_Type)
dh.Item_Fat_Content=label.fit_transform(dh.Item_Fat_Content)

In [125]:
dh

Item_Weight  Item_Fat_Content  Item_Visibility  Item_Type  Item_MRP  \
0          20.750                 1         0.007565         13  107.8622   
1           8.300                 4         0.038428          4   87.3198   
2          14.600                 1         0.099575         11  241.7538   
3           7.315                 1         0.015388         13  155.0340   
4          12.800                 2         0.118599          4  234.2300   
...           ...               ...              ...        ...       ...   
5676       10.500                 2         0.013496         13  141.3154   
5677        7.600                 2         0.142991         15  169.1448   
5678       10.000                 1         0.073529          8  118.7440   
5679       15.300                 2         0.000000          3  214.6218   
5680        9.500                 2         0.104720          3   79.7960   

      Outlet_Size  Outlet_Location_Type  Outlet_Type  
0               1                     0            1  
1               3                     1            1  
2               3                     2            0  
3               3                     1            1  
4               1                     2            3  
...           ...                   ...          ...  
5676            2                     0            1  
5677            1                     2            2  
5678            3                     1            1  
5679            3                     1            1  
5680            3                     1            1  

[5681 rows x 8 columns]

In [126]:
ypredd = model.predict(dh)

E:\Musics\Anaconda\Lib\site-packages\sklearn\base.py:432: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


In [127]:
ypredd

array([1800.42197422, 1338.75298964, 2284.4488038 , ..., 1639.05121108,
       3296.83359504, 1044.81552379])

In [128]:
dh['OutletSales'] = ypredd

In [129]:
dh

Item_Weight  Item_Fat_Content  Item_Visibility  Item_Type  Item_MRP  \
0          20.750                 1         0.007565         13  107.8622   
1           8.300                 4         0.038428          4   87.3198   
2          14.600                 1         0.099575         11  241.7538   
3           7.315                 1         0.015388         13  155.0340   
4          12.800                 2         0.118599          4  234.2300   
...           ...               ...              ...        ...       ...   
5676       10.500                 2         0.013496         13  141.3154   
5677        7.600                 2         0.142991         15  169.1448   
5678       10.000                 1         0.073529          8  118.7440   
5679       15.300                 2         0.000000          3  214.6218   
5680        9.500                 2         0.104720          3   79.7960   

      Outlet_Size  Outlet_Location_Type  Outlet_Type  OutletSales  
0               1                     0            1  1800.421974  
1               3                     1            1  1338.752990  
2               3                     2            0  2284.448804  
3               3                     1            1  2273.553101  
4               1                     2            3  5124.673719  
...           ...                   ...          ...          ...  
5676            2                     0            1  2352.557072  
5677            1                     2            2  3067.573712  
5678            3                     1            1  1639.051211  
5679            3                     1            1  3296.833595  
5680            3                     1            1  1044.815524  

[5681 rows x 9 columns]